server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: mancala-game
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
    url: jdbc:mysql://localhost/mancala
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  profiles:
    active: dev
    default: dev
springdoc:
  swagger-ui:
    url: /api-docs
    operations-sorter: method
  api-docs:
    path: /api-docs
application:
  version: 1.0.0
