server:
  port: 8080
  servlet:
    context-path: /api
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: mancala-game
  datasource:
    url: jdbc:h2:mem:mancala
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  profiles:
    active: dev
    default: dev
springdoc:
  swagger-ui:
    url: /api-docs
    operations-sorter: method
  api-docs:
    path: /api-docs
application:
  version: 1.0.0
